# Generated by Django 4.0.4 on 2022-05-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestRightModel',
            fields=[
                ('rights_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('user_name', models.CharField(help_text='Enter your name', max_length=50)),
                ('user_request', models.CharField(max_length=120)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('posted_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'user_request_rights',
            },
        ),
    ]
