# Generated by Django 4.0.4 on 2022-05-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userrequestrightmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontrolmodel',
            name='token_no',
        ),
        migrations.AddField(
            model_name='userrequestrightmodel',
            name='user_email',
            field=models.EmailField(help_text='Enter your email', max_length=60, null=True),
        ),
    ]
