# Generated by Django 4.0.3 on 2022-05-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_accesscontrolmodel_token_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadmodel',
            name='user_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
