# Generated by Django 4.0.4 on 2022-05-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_fileuploadmodel_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='userregistermodel',
            name='user_profile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
